/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "LangchainApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OpenaiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TavilyApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}