import type { DomainCategory } from "../types/domain.js";

export const DOMAIN_TAXONOMY: DomainCategory[] = [
  {
    id: "team_selection",
    label: "Team Selection",
    description:
      "How athletes are selected to represent the United States at the Olympic Games, " +
      "Paralympic Games, Pan American Games, World Championships, and other international " +
      "competitions. Covers NGB-specific selection procedures, qualification criteria, " +
      "discretionary selections, replacement athlete protocols, and nomination processes.",
    keywords: [
      "team selection",
      "selection procedures",
      "selection criteria",
      "Olympic trials",
      "Paralympic trials",
      "trials",
      "qualifying",
      "qualification",
      "qualified",
      "nomination",
      "nominated",
      "roster",
      "team roster",
      "selected",
      "not selected",
      "alternate",
      "replacement athlete",
      "discretionary selection",
      "automatic selection",
      "at-large",
      "wild card",
      "quota spot",
      "world ranking",
      "selection event",
      "trials results",
      "Pan American Games",
      "World Championships",
      "Olympic Games team",
      "Paralympic Games team",
      "make the team",
      "cut",
      "standard",
      "time standard",
      "qualifying standard",
      "minimum qualification score",
      "MQS",
      "OQT",
      "Olympic qualifying",
    ],
    escalationTargets: ["athlete_ombuds"],
  },
  {
    id: "dispute_resolution",
    label: "Dispute Resolution",
    description:
      "Processes available when athletes believe their rights have been violated, " +
      "including Section 9 arbitration under the Ted Stevens Olympic and Amateur Sports Act, " +
      "American Arbitration Association (AAA) proceedings, internal NGB grievance procedures, " +
      "USOPC complaint processes, and appeals to the Court of Arbitration for Sport (CAS).",
    keywords: [
      "dispute",
      "grievance",
      "arbitration",
      "Section 9",
      "Section 10",
      "Ted Stevens Act",
      "complaint",
      "protest",
      "appeal",
      "AAA",
      "American Arbitration Association",
      "CAS",
      "Court of Arbitration for Sport",
      "hearing",
      "panel",
      "arbitrator",
      "mediation",
      "resolution",
      "filed",
      "filing",
      "challenge",
      "challenged",
      "unfair",
      "rights violated",
      "denied opportunity",
      "decision appealed",
      "overturned",
      "reversed",
      "remedy",
      "relief",
      "injunction",
      "expedited hearing",
      "interim measures",
      "due process",
      "right to compete",
    ],
    escalationTargets: ["athlete_ombuds", "cas"],
  },
  {
    id: "safesport",
    label: "SafeSport",
    description:
      "Policies, reporting obligations, and protections related to abuse, misconduct, " +
      "and safety in sport. Administered by the U.S. Center for SafeSport. Covers " +
      "emotional, physical, and sexual misconduct; bullying; hazing; harassment; " +
      "minor athlete protections; and mandatory reporting obligations.",
    keywords: [
      "SafeSport",
      "safe sport",
      "abuse",
      "sexual abuse",
      "sexual misconduct",
      "emotional misconduct",
      "physical misconduct",
      "bullying",
      "hazing",
      "harassment",
      "sexual harassment",
      "misconduct",
      "minor athlete",
      "child protection",
      "mandatory reporting",
      "report abuse",
      "reporting",
      "investigation",
      "sanction",
      "sanctioned",
      "suspended",
      "banned",
      "temporary measures",
      "interim suspension",
      "SafeSport training",
      "SafeSport certification",
      "code of conduct",
      "appropriate boundaries",
      "power imbalance",
      "retaliation",
      "whistleblower",
      "clery act",
      "Title IX",
      "grooming",
      "inappropriate contact",
      "locker room policy",
      "travel policy",
      "one-on-one interactions",
    ],
    escalationTargets: ["safesport_center", "emergency_services"],
  },
  {
    id: "anti_doping",
    label: "Anti-Doping",
    description:
      "Rules, testing protocols, Therapeutic Use Exemptions (TUEs), whereabouts " +
      "requirements, and adjudication processes governed by the U.S. Anti-Doping Agency " +
      "(USADA) and the World Anti-Doping Agency (WADA). Covers prohibited substances, " +
      "sample collection, results management, and sanctions.",
    keywords: [
      "anti-doping",
      "doping",
      "drug test",
      "drug testing",
      "USADA",
      "WADA",
      "prohibited substance",
      "prohibited list",
      "banned substance",
      "TUE",
      "Therapeutic Use Exemption",
      "whereabouts",
      "ADAMS",
      "sample collection",
      "in-competition testing",
      "out-of-competition testing",
      "results management",
      "adverse analytical finding",
      "AAF",
      "atypical finding",
      "anti-doping rule violation",
      "ADRV",
      "sanction",
      "suspension",
      "period of ineligibility",
      "provisional suspension",
      "contaminated product",
      "supplement",
      "inadvertent doping",
      "filing failure",
      "missed test",
      "tampering",
      "World Anti-Doping Code",
      "USADA protocol",
      "biological passport",
      "ABP",
      "urine test",
      "blood test",
    ],
    escalationTargets: ["usada"],
  },
  {
    id: "eligibility",
    label: "Eligibility",
    description:
      "Athlete eligibility requirements set by the USOPC, National Governing Bodies, " +
      "and International Federations. Includes citizenship requirements, age requirements, " +
      "qualification standards, transfer of allegiance, amateur status, and competition " +
      "participation requirements.",
    keywords: [
      "eligibility",
      "eligible",
      "ineligible",
      "citizenship",
      "nationality",
      "passport",
      "transfer of allegiance",
      "age requirement",
      "age limit",
      "minimum age",
      "maximum age",
      "age eligibility",
      "qualification standard",
      "qualifying criteria",
      "amateur status",
      "professional",
      "college eligibility",
      "NCAA",
      "international federation rules",
      "IF rules",
      "competition license",
      "athlete registration",
      "membership",
      "good standing",
      "reinstatement",
      "gender eligibility",
      "classification",
      "Paralympic classification",
      "sport class",
    ],
    escalationTargets: ["athlete_ombuds"],
  },
  {
    id: "governance",
    label: "Governance",
    description:
      "The structure and obligations of the USOPC, NGBs, and related organizations " +
      "under the Ted Stevens Olympic and Amateur Sports Act and USOPC Bylaws. Covers " +
      "NGB certification and compliance requirements, board composition, organizational " +
      "structure, and Congressional oversight.",
    keywords: [
      "governance",
      "USOPC",
      "NGB",
      "National Governing Body",
      "bylaws",
      "Ted Stevens Act",
      "Olympic and Amateur Sports Act",
      "certification",
      "decertification",
      "compliance",
      "audit",
      "board of directors",
      "board composition",
      "athlete representation on board",
      "one-third representation",
      "organizational structure",
      "Congress",
      "Congressional oversight",
      "Section 8",
      "recognition",
      "recognized sport",
      "managed sport",
      "USOPC managed",
      "multi-sport organization",
      "MSO",
      "High Performance Plan",
      "HPP",
      "NGB compliance",
      "Code of Conduct",
      "conflict of interest",
      "fiduciary duty",
      "transparency",
      "accountability",
    ],
    escalationTargets: ["athletes_commission", "athlete_ombuds"],
  },
  {
    id: "athlete_rights",
    label: "Athlete Rights & Representation",
    description:
      "Athlete representation on boards and committees, including the Athletes' Advisory " +
      "Council (AAC) and Team USA Athletes' Commission. Marketing and sponsorship rights, " +
      "Name/Image/Likeness (NIL), the USOPC Athlete Bill of Rights, and athlete voice " +
      "in governance.",
    keywords: [
      "athlete rights",
      "Athlete Bill of Rights",
      "athlete representation",
      "Athletes' Advisory Council",
      "AAC",
      "Athletes' Commission",
      "athlete voice",
      "marketing rights",
      "sponsorship",
      "endorsement",
      "NIL",
      "Name Image Likeness",
      "Rule 40",
      "Rule 50",
      "commercial rights",
      "prize money",
      "athlete funding",
      "stipend",
      "grant",
      "Operation Gold",
      "athlete services",
      "health insurance",
      "mental health",
      "career transition",
      "athlete advisory",
      "vote",
      "election",
      "athlete board member",
      "one-third requirement",
      "collective bargaining",
      "athlete agreement",
      "team processing",
      "uniform",
      "podium",
      "medal ceremony",
      "expression",
      "protest",
      "demonstration",
    ],
    escalationTargets: ["athletes_commission", "athlete_ombuds"],
  },
];
