// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/sources": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/sources": {
    params: {};
  };
  "/admin/sources/new": {
    params: {};
  };
  "/admin/sources/bulk-import": {
    params: {};
  };
  "/admin/discoveries": {
    params: {};
  };
  "/admin/monitoring": {
    params: {};
  };
  "/admin/invites": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/api/chat/feedback": {
    params: {};
  };
  "/api/sources": {
    params: {};
  };
  "/api/access-request": {
    params: {};
  };
  "/api/documents/:key/url": {
    params: {
      "key": string;
    };
  };
  "/api/admin/sources": {
    params: {};
  };
  "/api/admin/sources/bulk": {
    params: {};
  };
  "/api/admin/sources/bulk-create": {
    params: {};
  };
  "/api/admin/sources/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/sources/:id/ingest": {
    params: {
      "id": string;
    };
  };
  "/api/admin/discoveries": {
    params: {};
  };
  "/api/admin/discoveries/bulk": {
    params: {};
  };
  "/api/admin/discoveries/:id": {
    params: {
      "id": string;
    };
  };
  "/api/admin/discovery/run": {
    params: {};
  };
  "/api/admin/invites": {
    params: {};
  };
  "/api/admin/monitoring": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/chat" | "/sources" | "/admin" | "/admin/sources" | "/admin/sources/new" | "/admin/sources/bulk-import" | "/admin/discoveries" | "/admin/monitoring" | "/admin/invites" | "/api/health" | "/api/chat" | "/api/chat/feedback" | "/api/sources" | "/api/access-request" | "/api/documents/:key/url" | "/api/admin/sources" | "/api/admin/sources/bulk" | "/api/admin/sources/bulk-create" | "/api/admin/sources/:id" | "/api/admin/sources/:id/ingest" | "/api/admin/discoveries" | "/api/admin/discoveries/bulk" | "/api/admin/discoveries/:id" | "/api/admin/discovery/run" | "/api/admin/invites" | "/api/admin/monitoring" | "/api/auth/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/sources.tsx": {
    id: "routes/sources";
    page: "/sources";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/sources" | "/admin/sources/new" | "/admin/sources/bulk-import" | "/admin/discoveries" | "/admin/monitoring" | "/admin/invites";
  };
  "routes/admin._index.tsx": {
    id: "routes/admin._index";
    page: "/admin";
  };
  "routes/admin.sources._index.tsx": {
    id: "routes/admin.sources._index";
    page: "/admin/sources";
  };
  "routes/admin.sources.new.tsx": {
    id: "routes/admin.sources.new";
    page: "/admin/sources/new";
  };
  "routes/admin.sources.bulk-import.tsx": {
    id: "routes/admin.sources.bulk-import";
    page: "/admin/sources/bulk-import";
  };
  "routes/admin.discoveries.tsx": {
    id: "routes/admin.discoveries";
    page: "/admin/discoveries";
  };
  "routes/admin.monitoring.tsx": {
    id: "routes/admin.monitoring";
    page: "/admin/monitoring";
  };
  "routes/admin.invites.tsx": {
    id: "routes/admin.invites";
    page: "/admin/invites";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat";
  };
  "routes/api.chat.feedback.ts": {
    id: "routes/api.chat.feedback";
    page: "/api/chat/feedback";
  };
  "routes/api.sources.ts": {
    id: "routes/api.sources";
    page: "/api/sources";
  };
  "routes/api.access-request.ts": {
    id: "routes/api.access-request";
    page: "/api/access-request";
  };
  "routes/api.documents.$key.url.ts": {
    id: "routes/api.documents.$key.url";
    page: "/api/documents/:key/url";
  };
  "routes/api.admin.sources.ts": {
    id: "routes/api.admin.sources";
    page: "/api/admin/sources";
  };
  "routes/api.admin.sources.bulk.ts": {
    id: "routes/api.admin.sources.bulk";
    page: "/api/admin/sources/bulk";
  };
  "routes/api.admin.sources.bulk-create.ts": {
    id: "routes/api.admin.sources.bulk-create";
    page: "/api/admin/sources/bulk-create";
  };
  "routes/api.admin.sources.$id.ts": {
    id: "routes/api.admin.sources.$id";
    page: "/api/admin/sources/:id";
  };
  "routes/api.admin.sources.$id.ingest.ts": {
    id: "routes/api.admin.sources.$id.ingest";
    page: "/api/admin/sources/:id/ingest";
  };
  "routes/api.admin.discoveries.ts": {
    id: "routes/api.admin.discoveries";
    page: "/api/admin/discoveries";
  };
  "routes/api.admin.discoveries.bulk.ts": {
    id: "routes/api.admin.discoveries.bulk";
    page: "/api/admin/discoveries/bulk";
  };
  "routes/api.admin.discoveries.$id.ts": {
    id: "routes/api.admin.discoveries.$id";
    page: "/api/admin/discoveries/:id";
  };
  "routes/api.admin.discovery.run.ts": {
    id: "routes/api.admin.discovery.run";
    page: "/api/admin/discovery/run";
  };
  "routes/api.admin.invites.ts": {
    id: "routes/api.admin.invites";
    page: "/api/admin/invites";
  };
  "routes/api.admin.monitoring.ts": {
    id: "routes/api.admin.monitoring";
    page: "/api/admin/monitoring";
  };
  "routes/api.auth.ts": {
    id: "routes/api.auth";
    page: "/api/auth/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/sources": typeof import("./app/routes/sources.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin._index": typeof import("./app/routes/admin._index.tsx");
  "routes/admin.sources._index": typeof import("./app/routes/admin.sources._index.tsx");
  "routes/admin.sources.new": typeof import("./app/routes/admin.sources.new.tsx");
  "routes/admin.sources.bulk-import": typeof import("./app/routes/admin.sources.bulk-import.tsx");
  "routes/admin.discoveries": typeof import("./app/routes/admin.discoveries.tsx");
  "routes/admin.monitoring": typeof import("./app/routes/admin.monitoring.tsx");
  "routes/admin.invites": typeof import("./app/routes/admin.invites.tsx");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/api.chat": typeof import("./app/routes/api.chat.ts");
  "routes/api.chat.feedback": typeof import("./app/routes/api.chat.feedback.ts");
  "routes/api.sources": typeof import("./app/routes/api.sources.ts");
  "routes/api.access-request": typeof import("./app/routes/api.access-request.ts");
  "routes/api.documents.$key.url": typeof import("./app/routes/api.documents.$key.url.ts");
  "routes/api.admin.sources": typeof import("./app/routes/api.admin.sources.ts");
  "routes/api.admin.sources.bulk": typeof import("./app/routes/api.admin.sources.bulk.ts");
  "routes/api.admin.sources.bulk-create": typeof import("./app/routes/api.admin.sources.bulk-create.ts");
  "routes/api.admin.sources.$id": typeof import("./app/routes/api.admin.sources.$id.ts");
  "routes/api.admin.sources.$id.ingest": typeof import("./app/routes/api.admin.sources.$id.ingest.ts");
  "routes/api.admin.discoveries": typeof import("./app/routes/api.admin.discoveries.ts");
  "routes/api.admin.discoveries.bulk": typeof import("./app/routes/api.admin.discoveries.bulk.ts");
  "routes/api.admin.discoveries.$id": typeof import("./app/routes/api.admin.discoveries.$id.ts");
  "routes/api.admin.discovery.run": typeof import("./app/routes/api.admin.discovery.run.ts");
  "routes/api.admin.invites": typeof import("./app/routes/api.admin.invites.ts");
  "routes/api.admin.monitoring": typeof import("./app/routes/api.admin.monitoring.ts");
  "routes/api.auth": typeof import("./app/routes/api.auth.ts");
};