#!/usr/bin/env bash
# pull-secrets.sh — Pull secrets from GCP Secret Manager into .env.local
#
# Usage:
#   ./scripts/pull-secrets.sh              # defaults to staging
#   ./scripts/pull-secrets.sh production   # pull from production
#
# Prerequisites:
#   - gcloud CLI installed and authenticated (`gcloud auth login`)
#   - Access to the target GCP project

set -euo pipefail

ENV="${1:-staging}"

case "$ENV" in
  staging)    PROJECT="gen-lang-client-0261549010" ;;
  production) PROJECT="usopc-athlete-support-prod" ;;
  *)
    echo "Usage: $0 [staging|production]"
    exit 1
    ;;
esac

PREFIX="usopc-${ENV}"
ENV_FILE=".env.local"

echo "Pulling secrets from GCP project: $PROJECT (${ENV})"
echo ""

# Secrets stored in GCP Secret Manager (must match infra/gcp/index.ts)
SECRETS=(
  DATABASE_URL
  OPENAI_API_KEY
  ANTHROPIC_API_KEY
  TAVILY_API_KEY
  RESEND_API_KEY
  AUTH_SECRET
  GITHUB_CLIENT_ID
  GITHUB_CLIENT_SECRET
  ADMIN_EMAILS
  SLACK_BOT_TOKEN
  SLACK_SIGNING_SECRET
  SLACK_APP_TOKEN
  LANGSMITH_API_KEY
  VOYAGE_API_KEY
  GOOGLE_AI_API_KEY
)

# Start with non-secret config from .env.example
cat > "$ENV_FILE" <<'HEADER'
# Auto-generated by scripts/pull-secrets.sh — do not commit
# Re-run: ./scripts/pull-secrets.sh [staging|production]

HEADER

# Pull each secret
PULLED=0
SKIPPED=0

for SECRET_NAME in "${SECRETS[@]}"; do
  GCP_SECRET_ID="${PREFIX}-${SECRET_NAME}"

  VALUE=$(gcloud secrets versions access latest \
    --secret="$GCP_SECRET_ID" \
    --project="$PROJECT" 2>/dev/null) || true

  if [ -n "$VALUE" ]; then
    echo "${SECRET_NAME}=${VALUE}" >> "$ENV_FILE"
    echo "  ✓ ${SECRET_NAME}"
    PULLED=$((PULLED + 1))
  else
    echo "  ✗ ${SECRET_NAME} (not found or no version)"
    SKIPPED=$((SKIPPED + 1))
  fi
done

# Append non-secret config
cat >> "$ENV_FILE" <<'CONFIG'

# LangSmith tracing
LANGCHAIN_TRACING_V2=true
LANGCHAIN_PROJECT=usopc-athlete-support

# Resource bindings (local dev — override if pointing at real GCP resources)
INGESTION_QUEUE_URL=placeholder
INGESTION_DLQ_URL=placeholder
DISCOVERY_FEED_QUEUE_URL=placeholder
DISCOVERY_FEED_DLQ_URL=placeholder
DOCUMENTS_BUCKET_NAME=placeholder

# Queue/Storage provider
STORAGE_PROVIDER=gcs
QUEUE_PROVIDER=pubsub

# App
NODE_ENV=development
LOG_LEVEL=debug
CONFIG

echo ""
echo "Done! Pulled ${PULLED} secrets, skipped ${SKIPPED}."
echo "Written to: ${ENV_FILE}"
echo ""
echo "To start dev: pnpm dev"
