#!/usr/bin/env bash
# sync-sst-env.sh — Extract SST resource bindings and secrets into .env.ec2.
# Run on the EC2 instance (requires AWS credentials and SST installed).
#
# Usage:
#   ./scripts/sync-sst-env.sh              # defaults to production
#   ./scripts/sync-sst-env.sh staging       # target a specific stage
#
# The generated .env.ec2 file is loaded by sourcing it before pm2 start,
# or by using: sst shell --stage <stage> -- pm2 start ecosystem.config.cjs
set -euo pipefail

STAGE="${1:-production}"
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$APP_DIR/.env.ec2"

cd "$APP_DIR"

echo "==> Extracting SST bindings for stage: $STAGE"
echo "# Auto-generated by sync-sst-env.sh — do not edit" > "$ENV_FILE"
echo "# Stage: $STAGE" >> "$ENV_FILE"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Extract all SST_RESOURCE_* env vars (resource bindings + secrets)
# Use node_modules/.bin/sst directly — npx may not be on PATH when running
# via SSH on Amazon Linux 2023 (nodejs20 installs npx-20, not npx).
SST="$APP_DIR/node_modules/.bin/sst"

# Install SST platform binaries if not already present — they are not
# committed to git and must be installed before `sst shell` can run.
echo "==> Installing SST platform binaries"
"$SST" install

# Capture raw sst shell output to a temp file for debugging.
# This lets us see exactly what SST outputs before filtering — useful for
# diagnosing cases where unexpected lines end up in .env.ec2.
SST_RAW=$(mktemp)
trap 'rm -f "$SST_RAW"' EXIT

echo "==> Running: sst shell --stage $STAGE -- env"
"$SST" shell --stage "$STAGE" -- env > "$SST_RAW"

echo "==> Raw sst shell output: $(wc -l < "$SST_RAW") lines total"
echo "==> First 10 lines of raw output:"
head -10 "$SST_RAW" || true
echo "==> Last 10 lines of raw output:"
tail -10 "$SST_RAW" || true
echo "==> Lines NOT matching SST_RESOURCE_|APP_URL|EMAIL_FROM (potential noise):"
grep -v '^SST_RESOURCE_\|^APP_URL=\|^EMAIL_FROM=' "$SST_RAW" | grep -v '^$' || echo "(none — output is clean)"

# Write filtered vars to env file
grep '^SST_RESOURCE_' "$SST_RAW" >> "$ENV_FILE"

# Also extract the computed APP_URL and EMAIL_FROM if set
grep -E '^(APP_URL|EMAIL_FROM)=' "$SST_RAW" >> "$ENV_FILE" 2>/dev/null || true

chmod 600 "$ENV_FILE"
echo "==> Written to $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
echo "==> Load with: set -a; source .env.ec2; set +a; pm2 start ecosystem.config.cjs"
