#!/usr/bin/env bash
# sync-sst-env.sh — Extract SST resource bindings and secrets into .env.ec2.
# Run on the EC2 instance (requires AWS credentials and SST installed).
#
# Usage:
#   ./scripts/sync-sst-env.sh              # defaults to production
#   ./scripts/sync-sst-env.sh staging       # target a specific stage
#
# The generated .env.ec2 file is loaded by sourcing it before pm2 start,
# or by using: sst shell --stage <stage> -- pm2 start ecosystem.config.cjs
set -euo pipefail

STAGE="${1:-production}"
APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$APP_DIR/.env.ec2"

cd "$APP_DIR"

echo "==> Extracting SST bindings for stage: $STAGE"
echo "# Auto-generated by sync-sst-env.sh — do not edit" > "$ENV_FILE"
echo "# Stage: $STAGE" >> "$ENV_FILE"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# Extract all SST_RESOURCE_* env vars (resource bindings + secrets)
# Use node_modules/.bin/sst directly — npx may not be on PATH when running
# via SSH on Amazon Linux 2023 (nodejs20 installs npx-20, not npx).
SST="$APP_DIR/node_modules/.bin/sst"

# Install SST platform binaries if not already present — they are not
# committed to git and must be installed before `sst shell` can run.
echo "==> Installing SST platform binaries"
"$SST" install

"$SST" shell --print-logs --stage "$STAGE" -- env | grep '^SST_RESOURCE_' >> "$ENV_FILE"

# Also extract the computed APP_URL and EMAIL_FROM if set
"$SST" shell --print-logs --stage "$STAGE" -- env | grep -E '^(APP_URL|EMAIL_FROM)=' >> "$ENV_FILE" 2>/dev/null || true

chmod 600 "$ENV_FILE"
echo "==> Written to $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
echo "==> Load with: set -a; source .env.ec2; set +a; pm2 start ecosystem.config.cjs"
